services:
  oci:
    build: .
    container_name: uichcc-oci
    ports:
      - "7891:9052"
    environment:
      - URL=<URL>
      - NAME=<USERNAME>
      - PASSWD=<PASSWORD>
      - GROUP=<GROUP>
      - TOTPTOKEN=<TOTPTOKEN>
    restart: always
